### ISSUE TITLE
option to name the zip?

### ISSUE THREAD

**Issue by zevaverbach** [ginfuru/alfred-zip-workflow#2]

**Comment by edheltzel** [comment]
pull request from @vitorgalvao should allow you to do this.

**Comment by vitorgalvao** [comment]
@ginfuru I think what @zevav is asking for is a way to give the zip a specific name (perhaps when more than one item is selected, in which case the default is `Archive.zip`). My PR doesn’t give that capability. That’s not a feature I’d currently care much for, even, as it adds an extra step.

**Comment by zevaverbach** [comment]
@vitorgalvao fair enough.  isn't there an extra step anyway, since you'll often want to rename your .zip?

**Comment by vitorgalvao** [comment]
@zevav I have no problem with extra steps when they’re required (e.g. [LabelColor](http://www.alfredforum.com/topic/1334-labelcolor-%E2%80%94-sets-a-label-color-for-selected-files-and-directories/)), but when it’s something you only sometimes needs, I have my reservations (perhaps @ginfuru shares the sentiment, since the option isn’t available). I had been using the workflow for less than five minutes before I submitted the PR, though, so perhaps you’re right. I’ll think about it and perhaps cook something up.

**Comment by edheltzel** [comment]
I'll have to agree. I also need to make sure I'm betting notified sooner if issues. Sorry folks

**Comment by chrisspiegl** [comment]
+1 I would love to see this feature as well!
